---
# tasks file for pacemaker

- name: OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - pacemaker
    - setup
    - service
    - config

# Debian(setup) specific tasks
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"

# RedHat(setup) specific tasks
- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"

# Common configuration tasks
- include: config.yml

# Common service tasks
- include: service.yml
